
services:
  server:
    build: ../server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
    volumes:
      - ../server:/srv
    command: npm run dev

  web:
    build: ../web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:4000/api
    volumes:
      - ../web:/usr/src/app
    command: npm run dev -- --host
